-- add policies
insert into public.policies(name, description, catalog_id, status)
values
  ('High temperature checks template', '', 25, 1),
  ('Humidity inline checks', '', 25, 1),
  ('Signalization', '', 25, 1),
  ('Complex', '', 25, 0)
;

insert into public.rules(policy_id, name)
values
  (1, 'Raise WARN'),
  (1, 'Raise CRITICAL'),
  (1, 'Clear'),
  (1, 'Notify when raise'),
  (1, 'Notify when clear'),
  (2, 'Raise CRITICAL'),
  (2, 'Clear'),
  (2, 'Notify when raise'),
  (2, 'Notify when clear'),
  (3, 'Raise CRITICAL and notify when open'),
  (3, 'Notify when clear'),
  (4, 'Complex condition')
;

insert into public.conditions(rule_id, type_id, parent_node_id, operator)
values
  (5, 6, null, null),
  (6, 3, null, null),
  (7, 6, null, null),
  (8, null, null, 1),
  (8, 7, 20, null),
  (8, 7, 20, null),
  (9, 7, null, null),
  (10, 4, null, null),
  (11, 6, null, null),
  (12, 7, null, null),
  (13, 7, null, null),
  (14, 7, null, null),
  (15, 7, null, null),
  (16, null, null, 0),
  (16, 5, 30, null),
  (16, 5, 30, null),
  (16, null, 30, 0),
  (16, 1, 33, null),
  (16, 4, 33, null)
;

insert into public.condition_params(condition_id, name, value)
values
  (17, 'policy', '1'),
  (17, 'metric', '1'),
  (17, 'minValue', '35'),
  (17, 'maxValue', '45'),
  (18, 'policy', '1'),
  (18, 'metric', '1'),
  (18, 'value', '45'),
  (19, 'policy', '1'),
  (19, 'metric', '1'),
  (19, 'minValue', '20'),
  (19, 'maxValue', '30'),
  (21, 'type', 'alarm'),
  (21, 'spec', '5'),
  (21, 'severity', 'WARN'),
  (22, 'type', 'alarm'),
  (22, 'spec', '5'),
  (22, 'severity', 'CRITICAL'),
  (23, 'type', 'alarm'),
  (23, 'spec', '5'),
  (23, 'severity', 'CLEAR'),
  (24, 'policy', '2'),
  (24, 'metric', '2'),
  (24, 'value', '20'),
  (24, 'object', '3'),
  (25, 'policy', '2'),
  (25, 'metric', '2'),
  (25, 'minValue', '20'),
  (25, 'maxValue', '80'),
  (25, 'object', '3'),
  (26, 'type', 'alarm'),
  (26, 'spec', '6'),
  (26, 'severity', 'CRITICAL'),
  (26, 'object', '3'),
  (27, 'type', 'alarm'),
  (27, 'spec', '6'),
  (27, 'severity', 'CLEAR'),
  (27, 'object', '3'),
  (28, 'type', 'event'),
  (28, 'spec', '3'),
  (29, 'type', 'alarm'),
  (29, 'spec', '3'),
  (29, 'severity', 'CLEAR'),
  (31, 'policy', '4'),
  (31, 'metric', '1'),
  (31, 'minValue', '20'),
  (31, 'maxValue', '30'),
  (31, 'object', '15'),
  (32, 'policy', '4'),
  (32, 'metric', '1'),
  (32, 'minValue', '20'),
  (32, 'maxValue', '30'),
  (32, 'object', '21'),
  (34, 'policy', '4'),
  (34, 'metric', '1'),
  (34, 'value', '20'),
  (34, 'object', '24'),
  (35, 'policy', '4'),
  (35, 'metric', '1'),
  (35, 'value', '30'),
  (35, 'object', '24')
;

insert into public.actions(rule_id, type, action_class, action_order)
values
  (5, 'true', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction', 1),
  (6, 'true', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction', 1),
  (7, 'true', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction', 1),
  (8, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1),
  (9, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1),
  (10, 'true', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction', 1),
  (11, 'true', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction', 1),
  (12, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1),
  (13, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1),
  (14, 'true', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction', 1),
  (14, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 2),
  (15, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1),
  (16, 'true', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1),
  (16, 'false', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction', 1)
;

insert into public.action_params(action_id, name, value)
values
  (36, 'spec', '5'),
  (36, 'severity', 'WARN'),
  (37, 'spec', '5'),
  (37, 'severity', 'CRITICAL'),
  (38, 'spec', '5'),
  (38, 'severity', 'CLEAR'),
  (39, 'message', 'High temperature!'),
  (39, 'preferredChannel', 'Email'),
  (40, 'message', 'Temperature normalized.'),
  (40, 'preferredChannel', 'Email'),
  (41, 'spec', '6'),
  (41, 'severity', 'CRITICAL'),
  (42, 'spec', '6'),
  (42, 'severity', 'CLEAR'),
  (43, 'message', 'Abnormal humidity!'),
  (43, 'preferredChannel', 'Email'),
  (44, 'message', 'Humidity normalized.'),
  (44, 'preferredChannel', 'Email'),
  (45, 'spec', '3'),
  (45, 'severity', 'CRITICAL'),
  (46, 'message', 'Break-in attempt!'),
  (46, 'preferredChannel', 'Email'),
  (47, 'message', 'Alarm caused by break-in attempt cleared.'),
  (47, 'preferredChannel', 'Email'),
  (48, 'message', 'Temperature in house is normal.'),
  (49, 'message', 'Temperature in the house is not complied with the specified norms!')
;
