INSERT INTO public.condition_classes (condition_id, context, name)
VALUES
  (17, 'core', 'com.netcracker.smarthome.business.policy.conditions.NonstrictRangeCondition'),
  (17, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.NonstrictRangeCondition'),
  (18, 'core', 'com.netcracker.smarthome.business.policy.conditions.GreaterThanCondition'),
  (18, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.GreaterThanCondition'),
  (19, 'core', 'com.netcracker.smarthome.business.policy.conditions.NonstrictRangeCondition'),
  (19, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.NonstrictRangeCondition'),
  (21, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (21, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.EventConditionWithSeverity'),
  (22, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (22, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.EventConditionWithSeverity'),
  (23, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (23, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.EventConditionWithSeverity'),
  (24, 'core', 'com.netcracker.smarthome.business.policy.conditions.LessThanCondition'),
  (24, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineLessThanCondition'),
  (25, 'core', 'com.netcracker.smarthome.business.policy.conditions.NonstrictRangeCondition'),
  (25, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineNonstrictRangeCondition'),
  (26, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (26, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineEventConditionWithSeverity'),
  (27, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (27, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineEventConditionWithSeverity'),
  (28, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (28, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.EventCondition'),
  (29, 'core', 'com.netcracker.smarthome.business.policy.conditions.EventCondition'),
  (29, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.EventConditionWithSeverity'),
  (31, 'core', 'com.netcracker.smarthome.business.policy.conditions.StrictRangeCondition'),
  (31, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineStrictRangeCondition'),
  (32, 'core', 'com.netcracker.smarthome.business.policy.conditions.StrictRangeCondition'),
  (32, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineStrictRangeCondition'),
  (34, 'core', 'com.netcracker.smarthome.business.policy.conditions.EqualsOrGreaterThanCondition'),
  (34, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineEqualsOrGreaterThanCondition'),
  (35, 'core', 'com.netcracker.smarthome.business.policy.conditions.LessThanCondition'),
  (35, 'ui', 'com.netcracker.smarthome.web.policy.components.conditions.InlineLessThanCondition');

INSERT INTO public.action_classes (action_id, context, name)
VALUES
  (36, 'core', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction'),
  (36, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.RaiseAlarmAction'),
  (37, 'core', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction'),
  (37, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.RaiseAlarmAction'),
  (38, 'core', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction'),
  (38, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.RaiseAlarmAction'),
  (39, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (39, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationViaChannelAction'),
  (40, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (40, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationViaChannelAction'),
  (41, 'core', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction'),
  (41, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.RaiseAlarmAction'),
  (42, 'core', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction'),
  (42, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.RaiseAlarmAction'),
  (43, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (43, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationViaChannelAction'),
  (44, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (44, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationViaChannelAction'),
  (45, 'core', 'com.netcracker.smarthome.business.policy.actions.RaiseAlarmAction'),
  (45, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.RaiseAlarmAction'),
  (46, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (46, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationViaChannelAction'),
  (47, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (47, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationViaChannelAction'),
  (48, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (48, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationAction'),
  (49, 'core', 'com.netcracker.smarthome.business.policy.actions.SendNotificationAction'),
  (49, 'ui', 'com.netcracker.smarthome.web.policy.components.actions.SendNotificationAction')
;

